.TH "label" 3 "Thu Jul 16 2020" "Version Test1" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
label
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Mouse was pressed\&. 
.PP
\fBParameters\fP
.RS 4
\fIe\fP mouse event 
.RE
.PP
Checks if slider is enabled, i\&.e\&., can interact with the slider thumbs\&.
.PP
Gets the current mouse position from the mouse event
.PP
Put focus on the slider
.PP
For all thumbs,
.PP
.IP "\(bu" 2
gets the bounding rectangle of the thumb,
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
