.TH "slider.lib.MetalMThumbSliderUI" 3 "Sun Jul 19 2020" "Version Test1" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib.MetalMThumbSliderUI
.SH SYNOPSIS
.br
.PP
.PP
Inherits MetalSliderUI, and \fBslider\&.lib\&.MThumbSliderAdditional\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetalMThumbSliderUI\fP (\fBMThumbSlider\fP \fBparent\fP)"
.br
.ti -1c
.RI "void \fBinstallUI\fP (JComponent c)"
.br
.ti -1c
.RI "void \fBuninstallUI\fP (JComponent c)"
.br
.ti -1c
.RI "void \fBcalculateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBpaint\fP (Graphics g, JComponent c)"
.br
.ti -1c
.RI "void \fBpaintThumb\fP (Graphics g)"
.br
.ti -1c
.RI "Point \fBcomputeX\fP (Point pOrig, Rectangle thumbRect, Rectangle trackRect)"
.br
.ti -1c
.RI "Point \fBcomputeY\fP (Point pOrig, Rectangle thumbRect, Rectangle trackRect)"
.br
.ti -1c
.RI "void \fBfillTrack\fP (Graphics g, Point t1, Point t2, Color fillColor)"
.br
.ti -1c
.RI "void \fBscrollByBlock\fP (int direction)"
.br
.ti -1c
.RI "void \fBscrollByUnit\fP (int direction)"
.br
.ti -1c
.RI "Rectangle \fBgetTrackRect\fP ()"
.br
.ti -1c
.RI "Dimension \fBgetThumbSize\fP ()"
.br
.ti -1c
.RI "int \fBxPositionForValue\fP (int value)"
.br
.ti -1c
.RI "int \fByPositionForValue\fP (int value)"
.br
.ti -1c
.RI "int \fBgetOrientation\fP ()"
.br
.ti -1c
.RI "Icon \fBgetVertThumbIcon\fP ()"
.br
.ti -1c
.RI "Icon \fBgetHorizThumbIcon\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ComponentUI \fBcreateUI\fP (JComponent c)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "MouseInputAdapter \fBcreateMThumbTrackListener\fP (JSlider slider)"
.br
.ti -1c
.RI "TrackListener \fBcreateTrackListener\fP (JSlider slider)"
.br
.ti -1c
.RI "void \fBinstallListeners\fP (JSlider slider)"
.br
.ti -1c
.RI "void \fBuninstallListeners\fP (JSlider slider)"
.br
.ti -1c
.RI "void \fBcalculateThumbLocation\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "\fBMThumbSliderAdditionalUI\fP \fBadditionalUi\fP"
.br
.ti -1c
.RI "MouseInputAdapter \fBmThumbTrackListener\fP"
.br
.ti -1c
.RI "final \fBMThumbSlider\fP \fBparent\fP"
.br
.ti -1c
.RI "Icon \fBthumbRenderer\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintHistogram\fP (Graphics g)"
.br
.ti -1c
.RI "void \fBpaintHistogramBar\fP (Graphics g, int y, int xFrom, int xTo, int height, int numberInRange)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file MetalMThumbSliderUI\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "slider\&.lib\&.MetalMThumbSliderUI\&.MetalMThumbSliderUI (\fBMThumbSlider\fP parent)"

.PP
Definition at line 30 of file MetalMThumbSliderUI\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.calculateGeometry ()"

.PP
Definition at line 87 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.calculateThumbLocation ()\fC [protected]\fP"

.PP
Definition at line 101 of file MetalMThumbSliderUI\&.java\&.
.SS "Point slider\&.lib\&.MetalMThumbSliderUI\&.computeX (Point pOrig, Rectangle thumbRect, Rectangle trackRect)"

.PP
Definition at line 229 of file MetalMThumbSliderUI\&.java\&.
.SS "Point slider\&.lib\&.MetalMThumbSliderUI\&.computeY (Point pOrig, Rectangle thumbRect, Rectangle trackRect)"

.PP
Definition at line 244 of file MetalMThumbSliderUI\&.java\&.
.SS "MouseInputAdapter slider\&.lib\&.MetalMThumbSliderUI\&.createMThumbTrackListener (JSlider slider)\fC [protected]\fP"

.PP
Definition at line 53 of file MetalMThumbSliderUI\&.java\&.
.SS "TrackListener slider\&.lib\&.MetalMThumbSliderUI\&.createTrackListener (JSlider slider)\fC [protected]\fP"

.PP
Definition at line 59 of file MetalMThumbSliderUI\&.java\&.
.SS "static ComponentUI slider\&.lib\&.MetalMThumbSliderUI\&.createUI (JComponent c)\fC [static]\fP"

.PP
Definition at line 25 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.fillTrack (Graphics g, Point t1, Point t2, Color fillColor)"

.PP
Definition at line 259 of file MetalMThumbSliderUI\&.java\&.
.SS "Icon slider\&.lib\&.MetalMThumbSliderUI\&.getHorizThumbIcon ()"

.PP
Definition at line 479 of file MetalMThumbSliderUI\&.java\&.
.SS "int slider\&.lib\&.MetalMThumbSliderUI\&.getOrientation ()"

.PP
Definition at line 469 of file MetalMThumbSliderUI\&.java\&.
.SS "Dimension slider\&.lib\&.MetalMThumbSliderUI\&.getThumbSize ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implements \fBslider\&.lib\&.MThumbSliderAdditional\fP\&.
.PP
Definition at line 442 of file MetalMThumbSliderUI\&.java\&.
.SS "Rectangle slider\&.lib\&.MetalMThumbSliderUI\&.getTrackRect ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Implements \fBslider\&.lib\&.MThumbSliderAdditional\fP\&.
.PP
Definition at line 432 of file MetalMThumbSliderUI\&.java\&.
.SS "Icon slider\&.lib\&.MetalMThumbSliderUI\&.getVertThumbIcon ()"

.PP
Definition at line 474 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.installListeners (JSlider slider)\fC [protected]\fP"

.PP
Definition at line 65 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.installUI (JComponent c)"

.PP
Definition at line 36 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.paint (Graphics g, JComponent c)"

.PP
Definition at line 108 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.paintHistogram (Graphics g)\fC [private]\fP"
Histogram 
.PP
Definition at line 318 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.paintHistogramBar (Graphics g, int y, int xFrom, int xTo, int height, int numberInRange)\fC [private]\fP"

.PP
Definition at line 370 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.paintThumb (Graphics g)"

.PP
Definition at line 224 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.scrollByBlock (int direction)"

.PP
\fBParameters\fP
.RS 4
\fIdirection\fP 
.RE
.PP

.PP
Definition at line 410 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.scrollByUnit (int direction)"

.PP
\fBParameters\fP
.RS 4
\fIdirection\fP 
.RE
.PP

.PP
Definition at line 419 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.uninstallListeners (JSlider slider)\fC [protected]\fP"

.PP
Definition at line 76 of file MetalMThumbSliderUI\&.java\&.
.SS "void slider\&.lib\&.MetalMThumbSliderUI\&.uninstallUI (JComponent c)"

.PP
Definition at line 45 of file MetalMThumbSliderUI\&.java\&.
.SS "int slider\&.lib\&.MetalMThumbSliderUI\&.xPositionForValue (int value)"

.PP
\fBParameters\fP
.RS 4
\fIvalue\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBslider\&.lib\&.MThumbSliderAdditional\fP\&.
.PP
Definition at line 453 of file MetalMThumbSliderUI\&.java\&.
.SS "int slider\&.lib\&.MetalMThumbSliderUI\&.yPositionForValue (int value)"

.PP
\fBParameters\fP
.RS 4
\fIvalue\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implements \fBslider\&.lib\&.MThumbSliderAdditional\fP\&.
.PP
Definition at line 464 of file MetalMThumbSliderUI\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMThumbSliderAdditionalUI\fP slider\&.lib\&.MetalMThumbSliderUI\&.additionalUi\fC [package]\fP"

.PP
Definition at line 21 of file MetalMThumbSliderUI\&.java\&.
.SS "MouseInputAdapter slider\&.lib\&.MetalMThumbSliderUI\&.mThumbTrackListener\fC [package]\fP"

.PP
Definition at line 22 of file MetalMThumbSliderUI\&.java\&.
.SS "final \fBMThumbSlider\fP slider\&.lib\&.MetalMThumbSliderUI\&.parent\fC [package]\fP"

.PP
Definition at line 23 of file MetalMThumbSliderUI\&.java\&.
.SS "Icon slider\&.lib\&.MetalMThumbSliderUI\&.thumbRenderer\fC [package]\fP"

.PP
Definition at line 105 of file MetalMThumbSliderUI\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
