.TH "slider.RSFSlider.ExampleFrame" 3 "Sun Jul 19 2020" "Version Test1" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.RSFSlider.ExampleFrame
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExampleFrame\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "\fBSliderPanel\fP \fBupperSlider\fP"
.br
.ti -1c
.RI "\fBSliderPanel\fP \fBlowerSlider\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitGUI\fP ()"
.br
.ti -1c
.RI "void \fBcreateUpperSlider\fP ()"
.br
.ti -1c
.RI "void \fBcreateLowerSlider\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ExampleFrame\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "slider\&.RSFSlider\&.ExampleFrame\&.ExampleFrame ()"

.PP
Definition at line 23 of file ExampleFrame\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void slider\&.RSFSlider\&.ExampleFrame\&.createLowerSlider ()\fC [private]\fP"

.PP
Definition at line 81 of file ExampleFrame\&.java\&.
.SS "void slider\&.RSFSlider\&.ExampleFrame\&.createUpperSlider ()\fC [private]\fP"

.PP
Definition at line 52 of file ExampleFrame\&.java\&.
.SS "void slider\&.RSFSlider\&.ExampleFrame\&.initGUI ()\fC [private]\fP"

.PP
Definition at line 28 of file ExampleFrame\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSliderPanel\fP slider\&.RSFSlider\&.ExampleFrame\&.lowerSlider\fC [package]\fP"

.PP
Definition at line 21 of file ExampleFrame\&.java\&.
.SS "\fBSliderPanel\fP slider\&.RSFSlider\&.ExampleFrame\&.upperSlider\fC [package]\fP"

.PP
Definition at line 20 of file ExampleFrame\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
