.TH "slider.lib.EditSliderDialog" 3 "Sun Jul 19 2020" "Version Test1" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib.EditSliderDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits JDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditSliderDialog\fP (\fBSliderParameters\fP sliderparam)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBconfirmActionPerformed\fP ()"
.br
.ti -1c
.RI "void \fBinitGUI\fP ()"
.br
.ti -1c
.RI "void \fBupdateGui\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "JButton \fBbConfirm\fP"
.br
.ti -1c
.RI "JLabel \fBnumberOfThumbs\fP"
.br
.ti -1c
.RI "JSpinner \fBnewNumberOfThumbs\fP"
.br
.ti -1c
.RI "JCheckBox \fBcbLogScale\fP"
.br
.ti -1c
.RI "\fBSliderParameters\fP \fBsliderParameters\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcolorButtonActionPerformed\fP (ActionEvent ev)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "JPanel \fBpColors\fP"
.br
.ti -1c
.RI "List< JButton > \fBcolorButtons\fP = new ArrayList()"
.br
.ti -1c
.RI "List< Color > \fBcolors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file EditSliderDialog\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "slider\&.lib\&.EditSliderDialog\&.EditSliderDialog (\fBSliderParameters\fP sliderparam)"
Constructor
.PP
\fBParameters\fP
.RS 4
\fIsliderparam\fP 
.RE
.PP

.PP
Definition at line 37 of file EditSliderDialog\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void slider\&.lib\&.EditSliderDialog\&.colorButtonActionPerformed (ActionEvent ev)\fC [private]\fP"
Color choosing action
.PP
\fBParameters\fP
.RS 4
\fIev\fP is an action event that stores the action command when a button is pressed\&. is a string\&. 
.RE
.PP

.PP
Definition at line 134 of file EditSliderDialog\&.java\&.
.SS "void slider\&.lib\&.EditSliderDialog\&.confirmActionPerformed ()\fC [protected]\fP"
Confirm Button Action 
.PP
Definition at line 55 of file EditSliderDialog\&.java\&.
.SS "void slider\&.lib\&.EditSliderDialog\&.initGUI ()\fC [protected]\fP"
Create Content 
.PP
Definition at line 75 of file EditSliderDialog\&.java\&.
.SS "void slider\&.lib\&.EditSliderDialog\&.updateGui ()\fC [protected]\fP"
Update content 
.PP
Definition at line 148 of file EditSliderDialog\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "JButton slider\&.lib\&.EditSliderDialog\&.bConfirm\fC [protected]\fP"

.PP
Definition at line 18 of file EditSliderDialog\&.java\&.
.SS "JCheckBox slider\&.lib\&.EditSliderDialog\&.cbLogScale\fC [protected]\fP"

.PP
Definition at line 23 of file EditSliderDialog\&.java\&.
.SS "List<JButton> slider\&.lib\&.EditSliderDialog\&.colorButtons = new ArrayList()\fC [private]\fP"

.PP
Definition at line 29 of file EditSliderDialog\&.java\&.
.SS "List<Color> slider\&.lib\&.EditSliderDialog\&.colors\fC [private]\fP"

.PP
Definition at line 30 of file EditSliderDialog\&.java\&.
.SS "JSpinner slider\&.lib\&.EditSliderDialog\&.newNumberOfThumbs\fC [protected]\fP"

.PP
Definition at line 21 of file EditSliderDialog\&.java\&.
.SS "JLabel slider\&.lib\&.EditSliderDialog\&.numberOfThumbs\fC [protected]\fP"

.PP
Definition at line 20 of file EditSliderDialog\&.java\&.
.SS "JPanel slider\&.lib\&.EditSliderDialog\&.pColors\fC [private]\fP"

.PP
Definition at line 28 of file EditSliderDialog\&.java\&.
.SS "\fBSliderParameters\fP slider\&.lib\&.EditSliderDialog\&.sliderParameters\fC [protected]\fP"

.PP
Definition at line 25 of file EditSliderDialog\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
