.TH "slider.lib" 3 "Sun Jul 19 2020" "Version Test1" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEditSliderDialog\fP"
.br
.ti -1c
.RI "class \fBMetalMThumbSliderUI\fP"
.br
.ti -1c
.RI "class \fBMThumbSlider\fP"
.br
.ti -1c
.RI "interface \fBMThumbSliderAdditional\fP"
.br
.ti -1c
.RI "class \fBMThumbSliderAdditionalUI\fP"
.br
.ti -1c
.RI "class \fBSliderPanel\fP"
.br
.ti -1c
.RI "class \fBSliderParameters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Slider Parameters\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
