.TH "slider.lib.MThumbSliderAdditionalUI" 3 "Sun Jul 19 2020" "Version 1.0" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib.MThumbSliderAdditionalUI
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThumbMovementHandler\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMThumbSliderAdditionalUI\fP (BasicSliderUI ui)"
.br
.ti -1c
.RI "void \fBinstallUI\fP (JComponent c)"
.br
.ti -1c
.RI "void \fBuninstallUI\fP (JComponent c)"
.br
.ti -1c
.RI "int \fBgetNumberOfThumbs\fP ()"
.br
.ti -1c
.RI "Rectangle[] \fBgetThumbsBodyBoundingBoxes\fP ()"
.br
.ti -1c
.RI "void \fBsetThumbLocationAt\fP (int leftThumbBodyBoundingBox, int upperThumbBodyBoundingBox, int indexOfCurrentThumb, \fBMThumbSlider\fP slider)"
.br
.ti -1c
.RI "Rectangle \fBgetSliderBodyBoundingBox\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetThumbsBodyBoundingBoxes\fP ()"
.br
.ti -1c
.RI "void \fBcalculateThumbsLocation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class provides the user interface behavior that is independent of the look and feel\&. 
.PP
Definition at line 27 of file MThumbSliderAdditionalUI\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "slider\&.lib\&.MThumbSliderAdditionalUI\&.MThumbSliderAdditionalUI (BasicSliderUI ui)"
Constructor: stores the user interface
.PP
\fBParameters\fP
.RS 4
\fIui\fP is the user interface 
.RE
.PP

.PP
Definition at line 47 of file MThumbSliderAdditionalUI\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void slider\&.lib\&.MThumbSliderAdditionalUI\&.calculateThumbsLocation ()\fC [protected]\fP"
Assures that the thumbtips are on the ticks of the slider and not some where in between\&.
.PP
\fB Description \fP
.PP
Gets the orientation of the slider, either vertical or horizontal
.IP "\(bu" 2
Vertical case is not implemented yet 
.PP
Assures that the thumbtips are on the ticks of the slider and not some where in between\&.
.PP
Gets the orientation of the slider, either vertical or horizontal (Vertical case \fBNot implemented yet\fP)
.PP
Gets the current thumb value
.PP
Gets the x position of thumb tip for that value on the slider body
.PP
Sets the position of the left side of the current thumb to the position of the tip - half the width of the thumb
.PP
Distinguishs if we have an odd number of thumbs or an even number of thumbs
.PP
.IP "\(bu" 2
case of even: the left half of the thumbs position will be below the slider and the right half of the thumbs position will be over the slider
.IP "  \(bu" 4
Example: 8-> 16 -> 8 (for four thumbs)
.PP

.IP "\(bu" 2
case of odd: the left half of the thumbs position will be below the slider, the middle thumb is in the middle of the slider body, and the right half of the thumbs position will be over the slider
.IP "  \(bu" 4
Example: 8-> 8-> 8 -> 8 (for five thumbs)
.PP

.PP

.PP
Definition at line 101 of file MThumbSliderAdditionalUI\&.java\&.
.SS "int slider\&.lib\&.MThumbSliderAdditionalUI\&.getNumberOfThumbs ()"
Gets the number of thumbs 
.PP
\fBReturns\fP
.RS 4
the number of thumbs 
.RE
.PP

.PP
Definition at line 194 of file MThumbSliderAdditionalUI\&.java\&.
.SS "Rectangle slider\&.lib\&.MThumbSliderAdditionalUI\&.getSliderBodyBoundingBox ()"
Gets the bounding box of the slider 
.PP
\fBReturns\fP
.RS 4
the bounding box of the slider 
.RE
.PP

.PP
Definition at line 271 of file MThumbSliderAdditionalUI\&.java\&.
.SS "Rectangle [] slider\&.lib\&.MThumbSliderAdditionalUI\&.getThumbsBodyBoundingBoxes ()"
Gets the bounding boxes of all thumbs
.PP
\fBReturns\fP
.RS 4
the bounding box of all thumbs 
.RE
.PP

.PP
Definition at line 204 of file MThumbSliderAdditionalUI\&.java\&.
.SS "void slider\&.lib\&.MThumbSliderAdditionalUI\&.installUI (JComponent c)"
Sets the number of thumbs, thumbs body bounding boxes, thumb movement handler
.PP
\fBParameters\fP
.RS 4
\fIc\fP is the parent component 
.RE
.PP

.PP
Definition at line 57 of file MThumbSliderAdditionalUI\&.java\&.
.SS "void slider\&.lib\&.MThumbSliderAdditionalUI\&.setThumbLocationAt (int leftThumbBodyBoundingBox, int upperThumbBodyBoundingBox, int indexOfCurrentThumb, \fBMThumbSlider\fP slider)"
This is the method for the cascading effect, there are two types of sliders, one vertical and another horizontal\&.
.PP
\fBParameters\fP
.RS 4
\fIleftThumbBodyBoundingBox\fP is the leftThumbBodyBoundingBox location of the thumb number indexOfCurrentThumb 
.br
\fIupperThumbBodyBoundingBox\fP is the upperThumbBodyBoundingBox location of the thumb number indexOfCurrentThumb 
.br
\fIindexOfCurrentThumb\fP is the indexOfCurrentThumb of the thumb whose location should be changed 
.br
\fIslider\fP is the slider to change
.RE
.PP
\fBDescription\fP Calculates the union of the old and the new bounding boxes of the thumbs to repaint the old one with the background and the new one with the thumb
.PP
Definition at line 221 of file MThumbSliderAdditionalUI\&.java\&.
.SS "void slider\&.lib\&.MThumbSliderAdditionalUI\&.setThumbsBodyBoundingBoxes ()\fC [protected]\fP"
Sets the bounding boxs of all thumbs 
.PP
Definition at line 83 of file MThumbSliderAdditionalUI\&.java\&.
.SS "void slider\&.lib\&.MThumbSliderAdditionalUI\&.uninstallUI (JComponent c)"
Unsets the thumbs body bounding boxes and the thumb movement handler (invalidating them)\&.
.PP
\fBParameters\fP
.RS 4
\fIc\fP is the parent component 
.RE
.PP

.PP
Definition at line 74 of file MThumbSliderAdditionalUI\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
