.TH "slider.lib.MThumbSliderAdditional" 3 "Sun Jul 19 2020" "Version Test1" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib.MThumbSliderAdditional
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Rectangle \fBgetTrackRect\fP ()"
.br
.ti -1c
.RI "Dimension \fBgetThumbSize\fP ()"
.br
.ti -1c
.RI "int \fBxPositionForValue\fP (int value)"
.br
.ti -1c
.RI "int \fByPositionForValue\fP (int value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBVersion\fP
.RS 4
1\&.0 09/08/99 
.RE
.PP

.PP
Definition at line 15 of file MThumbSliderAdditional\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Dimension slider\&.lib\&.MThumbSliderAdditional\&.getThumbSize ()"

.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "Rectangle slider\&.lib\&.MThumbSliderAdditional\&.getTrackRect ()"

.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "int slider\&.lib\&.MThumbSliderAdditional\&.xPositionForValue (int value)"

.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "int slider\&.lib\&.MThumbSliderAdditional\&.yPositionForValue (int value)"

.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
