.TH "slider.lib.SliderParameters" 3 "Sun Jul 19 2020" "Version 1.0" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib.SliderParameters
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSliderParameters\fP ()"
.br
.ti -1c
.RI "void \fBsetSliderColors\fP (int colorCode)"
.br
.ti -1c
.RI "int \fBgetNumberOfThumbs\fP ()"
.br
.ti -1c
.RI "void \fBsetNumberOfThumbs\fP (int \fBnumberOfThumbs\fP)"
.br
.ti -1c
.RI "ArrayList \fBgetSliderColors\fP ()"
.br
.ti -1c
.RI "void \fBsetSliderColorAt\fP (int index, Color color)"
.br
.ti -1c
.RI "Color \fBgetSliderColorAt\fP (int index)"
.br
.ti -1c
.RI "void \fBsetTrackFillColor\fP (Color color)"
.br
.ti -1c
.RI "Color \fBgetTrackFillColor\fP ()"
.br
.ti -1c
.RI "void \fBadditionalColors\fP (int n)"
.br
.ti -1c
.RI "void \fBsetSlider\fP (\fBMThumbSlider\fP \fBslider\fP)"
.br
.ti -1c
.RI "\fBMThumbSlider\fP \fBgetSlider\fP ()"
.br
.ti -1c
.RI "boolean \fBisLogScale\fP ()"
.br
.ti -1c
.RI "void \fBsetLogScale\fP (boolean \fBlogScale\fP)"
.br
.ti -1c
.RI "boolean \fBhasColor\fP ()"
.br
.ti -1c
.RI "int \fBgetMajorTickSpacing\fP ()"
.br
.ti -1c
.RI "void \fBsetMajorTickSpacing\fP (int \fBmajorTickSpacing\fP)"
.br
.ti -1c
.RI "int \fBgetMinorTickSpacing\fP ()"
.br
.ti -1c
.RI "void \fBsetMinorTickSpacing\fP (int \fBminorTickSpacing\fP)"
.br
.ti -1c
.RI "String \fBgetLabel\fP ()"
.br
.ti -1c
.RI "void \fBsetLabel\fP (String \fBlabel\fP)"
.br
.ti -1c
.RI "void \fBaddMouseAdapter\fP (MouseAdapter mouseAdapter)"
.br
.ti -1c
.RI "void \fBsetMouseListener\fP (JSlider \fBslider\fP)"
.br
.ti -1c
.RI "boolean \fBisShowDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetShowDialog\fP (boolean \fBshowDialog\fP)"
.br
.ti -1c
.RI "void \fBsetRange\fP (double \fBminimum\fP, double \fBmaximum\fP)"
.br
.ti -1c
.RI "void \fBsetMinimum\fP (double \fBminimum\fP)"
.br
.ti -1c
.RI "void \fBsetMaximum\fP (double \fBmaximum\fP)"
.br
.ti -1c
.RI "double \fBgetMinimum\fP ()"
.br
.ti -1c
.RI "double \fBgetMaximum\fP ()"
.br
.ti -1c
.RI "int \fBgetSliderMinimum\fP ()"
.br
.ti -1c
.RI "int \fBgetSliderMaximum\fP ()"
.br
.ti -1c
.RI "Hashtable< Integer, JLabel > \fBcreateLabels\fP (int minimumValue, int maximumValue)"
.br
.ti -1c
.RI "double \fBsliderValueToValue\fP (double value)"
.br
.ti -1c
.RI "double \fBvalueToSliderValue\fP (double value)"
.br
.ti -1c
.RI "int \fBgetExponent\fP (double value)  throws NumberFormatException     "
.br
.ti -1c
.RI "boolean \fBisCategoricalData\fP ()"
.br
.ti -1c
.RI "void \fBsetCategoricalData\fP (boolean \fBcategoricalData\fP)"
.br
.ti -1c
.RI "void \fBupdateSlider\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBMThumbSlider\fP \fBslider\fP = null"
.br
.ti -1c
.RI "int \fBmajorTickSpacing\fP = 10"
.br
.ti -1c
.RI "int \fBminorTickSpacing\fP = 1"
.br
.ti -1c
.RI "String \fBlabel\fP = ''"
.br
.ti -1c
.RI "int \fBnumberOfThumbs\fP = 2"
.br
.ti -1c
.RI "ArrayList< Color > \fBsliderColors\fP = null"
.br
.ti -1c
.RI "Color \fBtrackFillColor\fP = MetalLookAndFeel\&.getControlShadow()"
.br
.ti -1c
.RI "boolean \fBlogScale\fP"
.br
.ti -1c
.RI "boolean \fBshowDialog\fP = false"
.br
.ti -1c
.RI "boolean \fBcategoricalData\fP = false"
.br
.ti -1c
.RI "List< MouseAdapter > \fBmouseAdapters\fP = new ArrayList<>()"
.br
.ti -1c
.RI "double \fBsliderMinimum\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBsliderMaximum\fP = 10\&.0"
.br
.ti -1c
.RI "double \fBminimum\fP = 0\&.0"
.br
.ti -1c
.RI "double \fBmaximum\fP = 10\&.0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parameters for sliders 
.PP
Definition at line 17 of file SliderParameters\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "slider\&.lib\&.SliderParameters\&.SliderParameters ()"
Constructor 
.PP
Definition at line 40 of file SliderParameters\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void slider\&.lib\&.SliderParameters\&.additionalColors (int n)"
Set additional colors or delete unused colors\&.
.PP
\fBParameters\fP
.RS 4
\fIn\fP 
.RE
.PP

.PP
Definition at line 173 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.addMouseAdapter (MouseAdapter mouseAdapter)"

.PP
Definition at line 269 of file SliderParameters\&.java\&.
.SS "Hashtable<Integer, JLabel> slider\&.lib\&.SliderParameters\&.createLabels (int minimumValue, int maximumValue)"

.PP
Definition at line 335 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.getExponent (double value) throws NumberFormatException"

.PP
Definition at line 366 of file SliderParameters\&.java\&.
.SS "String slider\&.lib\&.SliderParameters\&.getLabel ()"

.PP
Definition at line 259 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.getMajorTickSpacing ()"

.PP
Definition at line 239 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.getMaximum ()"

.PP
Definition at line 320 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.getMinimum ()"

.PP
Definition at line 315 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.getMinorTickSpacing ()"

.PP
Definition at line 249 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.getNumberOfThumbs ()"
Returns number of thumbs of Slider
.PP
\fBReturns\fP
.RS 4
numberOfThumbs 
.RE
.PP

.PP
Definition at line 95 of file SliderParameters\&.java\&.
.SS "\fBMThumbSlider\fP slider\&.lib\&.SliderParameters\&.getSlider ()"
get parent slider
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line 210 of file SliderParameters\&.java\&.
.SS "Color slider\&.lib\&.SliderParameters\&.getSliderColorAt (int index)"

.PP
Definition at line 137 of file SliderParameters\&.java\&.
.SS "ArrayList slider\&.lib\&.SliderParameters\&.getSliderColors ()"

.PP
\fBReturns\fP
.RS 4
Colors Array 
.RE
.PP

.PP
Definition at line 113 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.getSliderMaximum ()"

.PP
Definition at line 330 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.getSliderMinimum ()"

.PP
Definition at line 325 of file SliderParameters\&.java\&.
.SS "Color slider\&.lib\&.SliderParameters\&.getTrackFillColor ()"

.PP
Definition at line 156 of file SliderParameters\&.java\&.
.SS "boolean slider\&.lib\&.SliderParameters\&.hasColor ()"

.PP
Definition at line 234 of file SliderParameters\&.java\&.
.SS "boolean slider\&.lib\&.SliderParameters\&.isCategoricalData ()"

.PP
Definition at line 390 of file SliderParameters\&.java\&.
.SS "boolean slider\&.lib\&.SliderParameters\&.isLogScale ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Definition at line 218 of file SliderParameters\&.java\&.
.SS "boolean slider\&.lib\&.SliderParameters\&.isShowDialog ()"

.PP
Definition at line 282 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setCategoricalData (boolean categoricalData)"

.PP
Definition at line 395 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setLabel (String label)"

.PP
Definition at line 264 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setLogScale (boolean logScale)"

.PP
\fBParameters\fP
.RS 4
\fIlogScale\fP 
.RE
.PP

.PP
Definition at line 226 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setMajorTickSpacing (int majorTickSpacing)"

.PP
Definition at line 244 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setMaximum (double maximum)"

.PP
Definition at line 309 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setMinimum (double minimum)"

.PP
Definition at line 303 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setMinorTickSpacing (int minorTickSpacing)"

.PP
Definition at line 254 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setMouseListener (JSlider slider)"

.PP
Definition at line 274 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setNumberOfThumbs (int numberOfThumbs)"
Sets the number of Thumbs of Slider
.PP
\fBParameters\fP
.RS 4
\fInumberOfThumbs\fP 
.RE
.PP

.PP
Definition at line 105 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setRange (double minimum, double maximum)"

.PP
Definition at line 292 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setShowDialog (boolean showDialog)"

.PP
Definition at line 287 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setSlider (\fBMThumbSlider\fP slider)"
set parent slider
.PP
\fBParameters\fP
.RS 4
\fIslider\fP 
.RE
.PP

.PP
Definition at line 200 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setSliderColorAt (int index, Color color)"
Set Color of desired position
.PP
\fBParameters\fP
.RS 4
\fIindex\fP 
.br
\fIcolor\fP 
.RE
.PP

.PP
Definition at line 124 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setSliderColors (int colorCode)"

.PP
Definition at line 44 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.setTrackFillColor (Color color)"

.PP
Definition at line 151 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.sliderValueToValue (double value)"

.PP
Definition at line 342 of file SliderParameters\&.java\&.
.SS "void slider\&.lib\&.SliderParameters\&.updateSlider ()"

.PP
Definition at line 400 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.valueToSliderValue (double value)"

.PP
Definition at line 354 of file SliderParameters\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "boolean slider\&.lib\&.SliderParameters\&.categoricalData = false\fC [protected]\fP"

.PP
Definition at line 29 of file SliderParameters\&.java\&.
.SS "String slider\&.lib\&.SliderParameters\&.label = ''\fC [protected]\fP"

.PP
Definition at line 23 of file SliderParameters\&.java\&.
.SS "boolean slider\&.lib\&.SliderParameters\&.logScale\fC [protected]\fP"

.PP
Definition at line 27 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.majorTickSpacing = 10\fC [protected]\fP"

.PP
Definition at line 21 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.maximum = 10\&.0\fC [protected]\fP"

.PP
Definition at line 35 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.minimum = 0\&.0\fC [protected]\fP"

.PP
Definition at line 34 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.minorTickSpacing = 1\fC [protected]\fP"

.PP
Definition at line 22 of file SliderParameters\&.java\&.
.SS "List<MouseAdapter> slider\&.lib\&.SliderParameters\&.mouseAdapters = new ArrayList<>()\fC [protected]\fP"

.PP
Definition at line 30 of file SliderParameters\&.java\&.
.SS "int slider\&.lib\&.SliderParameters\&.numberOfThumbs = 2\fC [protected]\fP"

.PP
Definition at line 24 of file SliderParameters\&.java\&.
.SS "boolean slider\&.lib\&.SliderParameters\&.showDialog = false\fC [protected]\fP"

.PP
Definition at line 28 of file SliderParameters\&.java\&.
.SS "\fBMThumbSlider\fP slider\&.lib\&.SliderParameters\&.slider = null\fC [protected]\fP"

.PP
Definition at line 20 of file SliderParameters\&.java\&.
.SS "ArrayList<Color> slider\&.lib\&.SliderParameters\&.sliderColors = null\fC [protected]\fP"

.PP
Definition at line 25 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.sliderMaximum = 10\&.0\fC [protected]\fP"

.PP
Definition at line 32 of file SliderParameters\&.java\&.
.SS "double slider\&.lib\&.SliderParameters\&.sliderMinimum = 0\&.0\fC [protected]\fP"

.PP
Definition at line 31 of file SliderParameters\&.java\&.
.SS "Color slider\&.lib\&.SliderParameters\&.trackFillColor = MetalLookAndFeel\&.getControlShadow()\fC [protected]\fP"

.PP
Definition at line 26 of file SliderParameters\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
