.TH "slider.lib.MThumbSlider" 3 "Sun Jul 19 2020" "Version Test1" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib.MThumbSlider
.SH SYNOPSIS
.br
.PP
.PP
Inherits JSlider\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMThumbSlider\fP (\fBSliderParameters\fP \fBsliderParameters\fP)"
.br
.ti -1c
.RI "void \fBupdateThumbs\fP (int n)"
.br
.ti -1c
.RI "int \fBgetThumbMoved\fP ()"
.br
.ti -1c
.RI "void \fBsetThumbMoved\fP (int \fBthumbMoved\fP)"
.br
.ti -1c
.RI "void \fBupdateUI\fP ()"
.br
.ti -1c
.RI "void \fBcreateLabels\fP ()"
.br
.ti -1c
.RI "String \fBgetUIClassID\fP ()"
.br
.ti -1c
.RI "int \fBgetNumberOfThumbs\fP ()"
.br
.ti -1c
.RI "int \fBgetValueAt\fP (int index)"
.br
.ti -1c
.RI "void \fBsetValueAt\fP (int value, int index, boolean recalculateGeometry)"
.br
.ti -1c
.RI "void \fBcalculateGeometry\fP ()"
.br
.ti -1c
.RI "void \fBsetMinimum\fP (double minimum)"
.br
.ti -1c
.RI "double \fBgetMinimumValue\fP ()"
.br
.ti -1c
.RI "void \fBsetMaximum\fP (double maximum)"
.br
.ti -1c
.RI "double \fBgetMaximumValue\fP ()"
.br
.ti -1c
.RI "Icon \fBgetThumbRendererAt\fP (int index)"
.br
.ti -1c
.RI "void \fBsetThumbRendererAt\fP (Icon icon, int index)"
.br
.ti -1c
.RI "int \fBgetMaxHistogram\fP ()"
.br
.ti -1c
.RI "void \fBsetMaxHistogram\fP (int \fBmaxHistogram\fP)"
.br
.ti -1c
.RI "boolean \fBisCategoricalData\fP ()"
.br
.ti -1c
.RI "int \fBgetBoxHeight\fP (int n)"
.br
.ti -1c
.RI "void \fBsetBoxHeight\fP (int box, int value)"
.br
.ti -1c
.RI "void \fBsetBoxHeightScaled\fP (int box, int value)"
.br
.ti -1c
.RI "void \fBsetNumberInRange\fP (List< Integer > box, List< Integer > \fBnumberInRange\fP)"
.br
.ti -1c
.RI "Integer \fBgetNumberInRange\fP (int box)"
.br
.ti -1c
.RI "int \fBcomputeHistogramHeightScaledByMaximum\fP (int \fBnumberInRange\fP)"
.br
.ti -1c
.RI "\fBSliderParameters\fP \fBgetSliderParameters\fP ()"
.br
.ti -1c
.RI "int \fBgetTicks\fP ()"
.br
.ti -1c
.RI "List< Integer > \fBgetTickValues\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static ImageIcon \fBcreateImageIcon\fP (String path)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBnumberOfThumbs\fP"
.br
.ti -1c
.RI "ArrayList< BoundedRangeModel > \fBsliderModels\fP"
.br
.ti -1c
.RI "ArrayList< Icon > \fBthumbRenderers\fP"
.br
.ti -1c
.RI "int \fBthumbMoved\fP = \-1"
.br
.ti -1c
.RI "HashMap< Integer, Integer > \fBboxHeight\fP = new HashMap<Integer, Integer>()"
.br
.ti -1c
.RI "HashMap< Integer, Integer > \fBnumberInRange\fP = new HashMap<Integer, Integer>()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateThumbs\fP ()"
.br
.ti -1c
.RI "BoundedRangeModel \fBgetModelAt\fP (int index)"
.br
.ti -1c
.RI "int \fBgetExponent\fP (double value)  throws NumberFormatException     "
.br
.ti -1c
.RI "Icon \fBgetThumbRenderer\fP (int number, int \fBnumberOfThumbs\fP)"
.br
.ti -1c
.RI "Icon \fBgetThumbRendererBestHorizontal\fP (int thumbNumber, int \fBnumberOfThumbs\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSliderParameters\fP \fBsliderParameters\fP = null"
.br
.ti -1c
.RI "boolean \fBrecomputeHistogram\fP = false"
.br
.ti -1c
.RI "int \fBmaxHistogram\fP = 1"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final String \fBuiClassID\fP = 'MThumbSliderUI'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Multi-Thumb Slider based on JSlider 
.PP
Definition at line 16 of file MThumbSlider\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "slider\&.lib\&.MThumbSlider\&.MThumbSlider (\fBSliderParameters\fP sliderParameters)"
Constructor
.PP
\fBParameters\fP
.RS 4
\fIsliderParameters\fP slider parameters 
.RE
.PP

.PP
Definition at line 40 of file MThumbSlider\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void slider\&.lib\&.MThumbSlider\&.calculateGeometry ()"

.PP
Definition at line 227 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.computeHistogramHeightScaledByMaximum (int numberInRange)"

.PP
Definition at line 502 of file MThumbSlider\&.java\&.
.SS "static ImageIcon slider\&.lib\&.MThumbSlider\&.createImageIcon (String path)\fC [static]\fP, \fC [protected]\fP"

.PP
 
.PP
Definition at line 343 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.createLabels ()"

.PP
Definition at line 151 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.createThumbs ()\fC [private]\fP"
Create thumbs\&. 
.PP
Definition at line 66 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.getBoxHeight (int n)"

.PP
Definition at line 444 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.getExponent (double value) throws NumberFormatException\fC [private]\fP"

.PP
Definition at line 323 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.getMaxHistogram ()"

.PP
Definition at line 425 of file MThumbSlider\&.java\&.
.SS "double slider\&.lib\&.MThumbSlider\&.getMaximumValue ()"

.PP
Definition at line 290 of file MThumbSlider\&.java\&.
.SS "double slider\&.lib\&.MThumbSlider\&.getMinimumValue ()"

.PP
Definition at line 255 of file MThumbSlider\&.java\&.
.SS "BoundedRangeModel slider\&.lib\&.MThumbSlider\&.getModelAt (int index)\fC [private]\fP"

.PP
Definition at line 302 of file MThumbSlider\&.java\&.
.SS "Integer slider\&.lib\&.MThumbSlider\&.getNumberInRange (int box)"

.PP
Definition at line 497 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.getNumberOfThumbs ()"

.PP
 
.PP
Definition at line 176 of file MThumbSlider\&.java\&.
.SS "\fBSliderParameters\fP slider\&.lib\&.MThumbSlider\&.getSliderParameters ()"

.PP
Definition at line 536 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.getThumbMoved ()"

.PP
Definition at line 125 of file MThumbSlider\&.java\&.
.SS "Icon slider\&.lib\&.MThumbSlider\&.getThumbRenderer (int number, int numberOfThumbs)\fC [private]\fP"

.PP
Definition at line 357 of file MThumbSlider\&.java\&.
.SS "Icon slider\&.lib\&.MThumbSlider\&.getThumbRendererAt (int index)"

.PP
\fBParameters\fP
.RS 4
\fIindex\fP 
.RE
.PP
\fBReturns\fP
.RS 4
thumb renderer 
.RE
.PP

.PP
Definition at line 312 of file MThumbSlider\&.java\&.
.SS "Icon slider\&.lib\&.MThumbSlider\&.getThumbRendererBestHorizontal (int thumbNumber, int numberOfThumbs)\fC [private]\fP"

.PP
Definition at line 379 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.getTicks ()"

.PP
Definition at line 541 of file MThumbSlider\&.java\&.
.SS "List<Integer> slider\&.lib\&.MThumbSlider\&.getTickValues ()"

.PP
Definition at line 553 of file MThumbSlider\&.java\&.
.SS "String slider\&.lib\&.MThumbSlider\&.getUIClassID ()"

.PP
Definition at line 164 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.getValueAt (int index)"

.PP
Definition at line 181 of file MThumbSlider\&.java\&.
.SS "boolean slider\&.lib\&.MThumbSlider\&.isCategoricalData ()"

.PP
Definition at line 439 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setBoxHeight (int box, int value)"

.PP
Definition at line 454 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setBoxHeightScaled (int box, int value)"

.PP
Definition at line 461 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setMaxHistogram (int maxHistogram)"

.PP
Definition at line 430 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setMaximum (double maximum)"

.PP
Definition at line 267 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setMinimum (double minimum)"

.PP
Definition at line 232 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setNumberInRange (List< Integer > box, List< Integer > numberInRange)"

.PP
Definition at line 469 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setThumbMoved (int thumbMoved)"

.PP
Definition at line 132 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setThumbRendererAt (Icon icon, int index)"

.PP
Definition at line 317 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.setValueAt (int value, int index, boolean recalculateGeometry)"

.PP
Definition at line 186 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.updateThumbs (int n)"

.PP
Definition at line 89 of file MThumbSlider\&.java\&.
.SS "void slider\&.lib\&.MThumbSlider\&.updateUI ()"

.PP
Definition at line 137 of file MThumbSlider\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "HashMap<Integer, Integer> slider\&.lib\&.MThumbSlider\&.boxHeight = new HashMap<Integer, Integer>()\fC [protected]\fP"

.PP
Definition at line 30 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.maxHistogram = 1\fC [private]\fP"

.PP
Definition at line 33 of file MThumbSlider\&.java\&.
.SS "HashMap<Integer, Integer> slider\&.lib\&.MThumbSlider\&.numberInRange = new HashMap<Integer, Integer>()\fC [protected]\fP"

.PP
Definition at line 31 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.numberOfThumbs\fC [protected]\fP"

.PP
Definition at line 24 of file MThumbSlider\&.java\&.
.SS "boolean slider\&.lib\&.MThumbSlider\&.recomputeHistogram = false\fC [private]\fP"

.PP
Definition at line 32 of file MThumbSlider\&.java\&.
.SS "ArrayList<BoundedRangeModel> slider\&.lib\&.MThumbSlider\&.sliderModels\fC [protected]\fP"

.PP
Definition at line 25 of file MThumbSlider\&.java\&.
.SS "\fBSliderParameters\fP slider\&.lib\&.MThumbSlider\&.sliderParameters = null\fC [private]\fP"

.PP
Definition at line 22 of file MThumbSlider\&.java\&.
.SS "int slider\&.lib\&.MThumbSlider\&.thumbMoved = \-1\fC [protected]\fP"

.PP
Definition at line 28 of file MThumbSlider\&.java\&.
.SS "ArrayList<Icon> slider\&.lib\&.MThumbSlider\&.thumbRenderers\fC [protected]\fP"

.PP
Definition at line 26 of file MThumbSlider\&.java\&.
.SS "final String slider\&.lib\&.MThumbSlider\&.uiClassID = 'MThumbSliderUI'\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 20 of file MThumbSlider\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
