.TH "slider.lib.MThumbSliderAdditional" 3 "Sun Jul 19 2020" "Version 1.0" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.lib.MThumbSliderAdditional
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Rectangle \fBgetTrackRect\fP ()"
.br
.ti -1c
.RI "Dimension \fBgetThumbSize\fP ()"
.br
.ti -1c
.RI "int \fBxPositionForValue\fP (int value)"
.br
.RI "Gets the x position of thumb tip for that value on the slider body\&. "
.ti -1c
.RI "int \fByPositionForValue\fP (int value)"
.br
.RI "Gets the y position of thumb tip for that value on the slider body\&. "
.in -1c
.SH "Detailed Description"
.PP 
This interface should be implemented by the following look and feel classes: BasicMThumbSliderUI, \fBMetalMThumbSliderUI\fP, and MotifMThumbSliderUI\&. Nevertheless, currently only the \fBMetalMThumbSliderUI\fP is implemented\&. 
.PP
Definition at line 9 of file MThumbSliderAdditional\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "Dimension slider\&.lib\&.MThumbSliderAdditional\&.getThumbSize ()"
Sets the bounding boxs of all thumbs 
.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "Rectangle slider\&.lib\&.MThumbSliderAdditional\&.getTrackRect ()"
Gets the bounding box of the slider 
.PP
\fBReturns\fP
.RS 4
the bounding box of the slider 
.RE
.PP

.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "int slider\&.lib\&.MThumbSliderAdditional\&.xPositionForValue (int value)"

.PP
Gets the x position of thumb tip for that value on the slider body\&. 
.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.
.SS "int slider\&.lib\&.MThumbSliderAdditional\&.yPositionForValue (int value)"

.PP
Gets the y position of thumb tip for that value on the slider body\&. 
.PP
Implemented in \fBslider\&.lib\&.MetalMThumbSliderUI\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
