.TH "slider.RSFSlider.Example" 3 "Sun Jul 19 2020" "Version 1.0" "RSFslider" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slider.RSFSlider.Example
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String args[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Example\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void slider\&.RSFSlider\&.Example\&.main (String args[])\fC [static]\fP"

.PP
Definition at line 6 of file Example\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RSFslider from the source code\&.
